spring:
  datasource:
    url: jdbc:mysql://localhost:3306/projekt?useSSL=false&serverTimezone=UTC
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    content negotiation:
      defaultContentType: application/json
  servlet:
    multipart: enabled
    enabled: true
    max-file-size: 100000000000MB
    max-request-size: 100000000000MB